services:
  karma_api:
    image: avr24rakuten/karma_api:__VERSION__
    container_name: karma_api
    networks:
      - karma_network
    ports:
      - 8000:8000
    volumes:
      - karma_shared_volume:/karma/shared
  karma_db:
    image: avr24rakuten/karma_db:__VERSION__
    container_name: karma_db
    networks:
      - karma_network
    volumes:
      - karma_shared_volume:/karma/shared
  karma_model:
    image: avr24rakuten/karma_model:__VERSION__
    container_name: karma_model
    networks:
      - karma_network
    volumes:
      - karma_shared_volume:/karma/shared
networks:
  karma_network:
volumes:
  karma_shared_volume:
    external: true
    name: karma_shared_volume