# Official ubuntu image
FROM ubuntu:20.04

COPY karma/docker/karma_model/requirements.txt ./
COPY karma/model_api ./app/

RUN apt update && apt install python3-pip -y && pip install -r requirements.txt
RUN apt-get install -y curl

EXPOSE 8081

WORKDIR /app

CMD uvicorn model_api:server --host 0.0.0.0 --port 8081