# Official Mysql image
FROM mysql:latest

# ADD ARGUMENT FOR DOCKER IMAGE BUILD THEN CREATE ENV VARIABLE AVAILABLE FOR KARMA
ARG MYSQL_ROOT_PASSWORD
ENV MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD

# # SQL init script
COPY docker/karma_db/init_common.sql /docker-entrypoint-initdb.d/
COPY docker/karma_db/init_int.sql /docker-entrypoint-initdb.d/