name: Push Main Branch
on:
  pull_request:
    branches:
      - main

jobs:
  pr_to_main:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get host IP
        id: hostip
        run: echo "HOST_IP=$(hostname -I | awk '{print $1}')" >> $GITHUB_ENV

      - name: Run Bash Setup Integration Script
        env:
          SECRET_JWT_KEY: ${{ secrets.SECRET_JWT_KEY }}
          MYSQL_ROOT_PASSWORD_INT: ${{ secrets.MYSQL_ROOT_PASSWORD_INT }}
          MYSQL_ROOT_PASSWORD_PROD: ${{ secrets.MYSQL_ROOT_PASSWORD_PROD }}
        run: ./setup_int.sh 1

      - name: Unit Tests Step (Pytest)
        run: docker exec karma_api bash -c "python3 -m pytest test_rakuten_api.py"

      - name: Run Bash Setup Test Integration Script
        env:
          MYSQL_ROOT_PASSWORD_INT: ${{ secrets.MYSQL_ROOT_PASSWORD_INT }}
          HOST_IP: ${{ env.HOST_IP }}
        run: ./setup_test_int.sh

      - name: API Tests Step (Pytest)
        run: docker exec karma_test_int bash -c "python3 -m pytest test_func_int.py"

      - name: Container API Test Stop
        run: |
            docker container rm karma_test_int || true
            docker container rm karma_test_int || true
            docker image rm karma_test_int || true

      - name: Docker Compose Down
        run: docker-compose -f docker/docker-compose-karma-int.yml down