name: Push Release To Prod
on:
  release:
    types: [published]

jobs:
    realease:
        runs-on: ubuntu-latest
        steps:
          - name: Login to Docker Hub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
    
          - name: Checkout code
            uses: actions/checkout@v2
            with:
              ref: main
    
          - name: Run Bash Setup Test Integration Script
            run: ./build_images_prod.sh
    
          - name: Push Docker image karma_api to Docker Hub
            run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/karma_api:latest
            
          - name: Push Docker image karma_db to Docker Hub
            run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/karma_db:latest
    
          - name: Push Docker image karma_model to Docker Hub
            run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/karma_model:latest