name: Push Prod
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Bash Setup Integration Script
        env:
          SECRET_JWT_KEY: ${{ secrets.SECRET_JWT_KEY }}
          MYSQL_ROOT_PASSWORD_INT: ${{ secrets.MYSQL_ROOT_PASSWORD_INT }}
          MYSQL_ROOT_PASSWORD_PROD: ${{ secrets.MYSQL_ROOT_PASSWORD_PROD }}
        run: ./setup_int.sh 1

      - name: Unit Tests Step (Pytest)
        run: docker exec karma_api bash -c "python3 -m pytest test_rakuten_api.py"

      - name: Docker Compose Down
        run: docker-compose -f docker/docker-compose-karma-int.yml down

      - name: Build Docker API Test Int Image
        run: docker build -f docker/karma_test_int/Dockerfile -t karma_test_int .

      - name: Run Bash Setup Test Integration Script
        env:
          MYSQL_ROOT_PASSWORD_INT: ${{ secrets.MYSQL_ROOT_PASSWORD_INT }}
        run: ./setup_test_int.sh

      - name: API Step (Pytest)
        run: docker exec karma_test_int bash -c "python3 -m pytest test_func_int.py"