name: New Prod Release
on:
  release:
    types: [published]

jobs:
  new_prod_realease:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Run Bash Setup Test Integration Script
        run: ./build_images_prod.sh

      - name: Push Docker image karma_api to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/karma:karma_api
        
      - name: Push Docker image karma_db to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/karma:karma_db

      - name: Push Docker image karma_model to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/karma:karma_model